const layouts=[
[[1,1,1,1,1,1,1,1,1,1],[1,2,0,0,1,0,0,0,0,1],[1,0,1,0,1,0,1,1,0,1],[1,0,1,0,0,0,0,1,0,1],[1,0,1,1,1,1,0,1,0,1],[1,0,0,0,0,0,0,1,0,1],[1,0,1,1,1,1,0,0,0,1],[1,0,0,0,0,1,0,1,0,1],[1,0,1,0,0,0,0,1,0,1],[1,1,1,1,1,1,1,1,1,1]],
[[1,1,1,1,1,1,1,1,1,1],[1,2,0,0,0,1,0,0,0,1],[1,1,1,0,0,1,0,1,0,1],[1,0,0,0,1,1,0,1,0,1],[1,0,1,0,0,0,0,1,0,1],[1,0,1,1,1,1,0,0,0,1],[1,0,0,0,0,1,1,1,0,1],[1,0,1,1,0,0,0,1,0,1],[1,0,0,0,0,1,0,0,0,1],[1,1,1,1,1,1,1,1,1,1]],
[[1,1,1,1,1,1,1,1,1,1],[1,2,0,1,0,0,0,1,0,1],[1,0,0,1,0,1,0,1,0,1],[1,1,0,0,0,1,0,0,0,1],[1,0,0,1,1,1,1,1,0,1],[1,0,1,1,0,0,0,0,0,1],[1,0,0,0,0,1,1,1,0,1],[1,1,1,1,0,0,0,1,0,1],[1,0,0,0,0,1,0,0,0,1],[1,1,1,1,1,1,1,1,1,1]],
[[1,1,1,1,1,1,1,1,1,1],[1,2,0,0,1,0,0,1,0,1],[1,1,1,0,1,0,1,1,0,1],[1,0,0,0,0,0,0,0,0,1],[1,0,1,1,1,1,1,1,0,1],[1,0,0,0,0,0,0,1,0,1],[1,1,1,1,0,1,0,1,0,1],[1,0,0,0,0,1,0,0,0,1],[1,0,1,0,0,0,0,1,0,1],[1,1,1,1,1,1,1,1,1,1]],
[[1,1,1,1,1,1,1,1,1,1],[1,2,0,0,0,0,1,0,0,1],[1,1,1,1,0,1,1,0,1,1],[1,0,0,0,0,0,0,0,0,1],[1,0,1,1,1,1,0,1,0,1],[1,0,0,0,0,1,0,0,0,1],[1,1,1,1,0,1,1,1,0,1],[1,0,0,0,0,0,0,1,0,1],[1,0,1,0,0,0,0,0,0,1],[1,1,1,1,1,1,1,1,1,1]]
];
const maze=document.getElementById('maze'),startBtn=document.getElementById('startBtn'),restartBtn=document.getElementById('restartBtn'),scoreEl=document.getElementById('score'),roundEl=document.getElementById('round'),livesEl=document.getElementById('lives'),comboEl=document.getElementById('combo'),message=document.getElementById('message'),board=document.getElementById('leaderboardList');
let round=1,score=0,lives=3,combo=1,running=false,player,enemy,enemies=[],points=[],bonus=null,timer,roundTimer;
const freeCells=()=>{const out=[];const grid=layouts[round-1];grid.forEach((row,r)=>row.forEach((v,c)=>{if(v===0)out.push({r,c})}));return out};
const key=p=>`${p.r},${p.c}`;const shuffle=a=>a.sort(()=>Math.random()-.5);
function setupRound(){clearInterval(timer);clearTimeout(roundTimer);const grid=layouts[round-1],cells=shuffle(freeCells());player={r:1,c:1};points=cells.filter(p=>key(p)!==key(player)).slice(0,Math.min(12,7+round));bonus=round>=2?cells.find(p=>!points.some(x=>key(x)===key(p))&&key(p)!==key(player)):null;const enemyCount=Math.min(round,4);enemies=cells.filter(p=>key(p)!==key(player)&&!points.some(x=>key(x)===key(p))&&(!bonus||key(p)!==key(bonus))).slice(0,enemyCount);render();timer=setInterval(moveEnemies,Math.max(220,620-round*75));message.textContent=`Round ${round}: collect everything!`}
function render(){maze.innerHTML='';const grid=layouts[round-1];for(let r=0;r<10;r++)for(let c=0;c<10;c++){const cell=document.createElement('div');cell.className='cell';if(grid[r][c]===1)cell.classList.add('wall');if(points.some(p=>key(p)===`${r},${c}`))cell.classList.add('point');if(bonus&&key(bonus)===`${r},${c}`)cell.classList.add('bonus');if(enemies.some(e=>key(e)===`${r},${c}`))cell.classList.add('enemy');if(player&&key(player)===`${r},${c}`)cell.classList.add('player');maze.appendChild(cell)}}
function updateHUD(){scoreEl.textContent=score;roundEl.textContent=`${round} / 5`;livesEl.textContent='❤️'.repeat(lives)+'🖤'.repeat(3-lives);comboEl.textContent=`x${combo}`}
function reset(){clearInterval(timer);clearTimeout(roundTimer);round=1;score=0;lives=3;combo=1;running=false;startBtn.hidden=false;restartBtn.hidden=true;message.textContent='Ready?';setupRound();updateHUD()}
function start(){reset();running=true;startBtn.hidden=true;restartBtn.hidden=false;setupRound()}
function finish(win){running=false;clearInterval(timer);if(win){score+=250*round;updateHUD();if(round<5){message.textContent=`Round ${round} cleared! +${250*round} bonus — get ready!`;round++;combo=1;roundTimer=setTimeout(setupRound,1600);running=true}else{message.textContent=`🏆 YOU BEAT SNACK MAN! Final score: ${score}`;restartBtn.hidden=false;saveScore();}}else{message.textContent=`💥 Game over! Final score: ${score}`;restartBtn.hidden=false;saveScore()}}
function hitEnemy(){lives--;combo=1;updateHUD();if(lives<=0){finish(false);return}player={r:1,c:1};message.textContent=`Ouch! ${lives} lives left.`;render()}
function move(dr,dc){if(!running)return;const grid=layouts[round-1],r=player.r+dr,c=player.c+dc;if(r<0||c<0||r>=10||c>=10||grid[r][c]===1)return;player={r,c};const pi=points.findIndex(p=>key(p)===key(player));if(pi>=0){points.splice(pi,1);score+=10*combo;combo=Math.min(5,combo+1)}if(bonus&&key(bonus)===key(player)){score+=100;bonus=null;message.textContent='⭐ Bonus snack! +100';}if(enemies.some(e=>key(e)===key(player))){hitEnemy();return}updateHUD();render();if(points.length===0)finish(true)}
function moveEnemies(){if(!running)return;const grid=layouts[round-1];enemies=enemies.map(enemy=>{const options=[[1,0],[-1,0],[0,1],[0,-1]].map(([dr,dc])=>({r:enemy.r+dr,c:enemy.c+dc})).filter(p=>p.r>=0&&p.c>=0&&p.r<10&&p.c<10&&grid[p.r][p.c]!==1);if(!options.length)return enemy;options.sort((a,b)=>(Math.abs(a.r-player.r)+Math.abs(a.c-player.c))-(Math.abs(b.r-player.r)+Math.abs(b.c-player.c)));return Math.random()<.72?options[0]:options[Math.floor(Math.random()*options.length)]});if(enemies.some(e=>key(e)===key(player)))hitEnemy();render()}
function saveScore(){const name=prompt('You made the Hall of Fame! Enter your name:','Player')?.trim()||'Player';const scores=JSON.parse(localStorage.getItem('snackManScores')||'[]');scores.push({name,score,round:new Date().toLocaleDateString()});scores.sort((a,b)=>b.score-a.score);localStorage.setItem('snackManScores',JSON.stringify(scores.slice(0,10)));renderBoard()}
function renderBoard(){const scores=JSON.parse(localStorage.getItem('snackManScores')||'[]');board.innerHTML=scores.length?scores.map((s,i)=>`<li><strong>${escapeHTML(s.name)}</strong> — ${s.score} pts <small>(saved ${s.round})</small></li>`).join(''):'<li>No scores yet — be the first!</li>'}
function escapeHTML(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.addEventListener('keydown',e=>{const m={ArrowUp:[-1,0],ArrowDown:[1,0],ArrowLeft:[0,-1],ArrowRight:[0,1],w:[-1,0],s:[1,0],a:[0,-1],d:[0,1]};if(m[e.key]){e.preventDefault();move(...m[e.key])}});document.querySelectorAll('[data-move]').forEach(b=>b.addEventListener('click',()=>{const m={up:[-1,0],down:[1,0],left:[0,-1],right:[0,1]};move(...m[b.dataset.move])}));startBtn.onclick=start;restartBtn.onclick=start;document.getElementById('clearBoard').onclick=()=>{localStorage.removeItem('snackManScores');renderBoard()};reset();renderBoard();
